from enum import Enum


class Rarity(Enum):
    ANY = -2
    NONE = -1
    COMMON = 0
    RARE = 1
    SUPREME = 2
    FANTASTIC = 3


class ItemTemplateType (Enum):
    none = -1
    hollow = 1
    weapon_slash = 2
    shield = 3
    armour = 4
    food = 5
    magic = 6
    tool_field = 7
    body_part = 8
    inventory = 9
    tool_mining = 10
    tool_carpentry = 11
    tool_smithing = 12
    weapon_pierce = 13
    weapon_crush = 14
    weapon_axe = 15
    weapon_sword = 16
    weapon_knife = 17
    weapon_misc = 18
    tool_digging = 19
    seed = 20
    wood = 21
    metal = 22
    leather = 23
    cloth = 24
    stone = 25
    liquid = 26
    melting = 27
    meat = 28
    vegetable = 29
    pottery = 30
    no_take = 31
    light = 32
    container_liquid = 33
    liquid_inflammable = 34
    weapon_melee = 35
    fish = 36
    weapon = 37
    tool = 38
    lock = 39
    indestructible = 40
    key = 41
    no_drop = 42
    dust = 43
    repairable = 44
    temporary = 45
    combine = 46
    lockable = 47
    has_data = 48
    outside_only = 49
    coin = 50
    turnable = 51
    decoration = 52
    full_price = 53
    no_rename = 54
    low_nutrition = 55
    draggable = 56
    village_deed = 57
    home_stead_deed = 58
    always_poll = 59
    floating = 60
    no_trade = 61
    butchered = 62
    no_put = 63
    lead_creature = 64
    fire = 65
    domain = 66
    use_ground_only = 67
    huge_altar = 68
    artifact = 69
    unique = 70
    destroy_huge_altar = 71
    pass_full_data = 72
    form = 73
    medium_nutrition = 74
    good_nutrition = 75
    high_nutrition = 76
    food_maker = 77
    herb = 78
    poison = 79
    fruit = 80
    desc_is_exam = 81
    dish = 82
    server_bound = 83
    two_handed = 84
    kingdom_marker = 85
    destroyable = 86
    material_price_effect = 87
    liquid_cooking = 88
    positive_decay = 89
    liquid_drinkable = 90
    color = 91
    colorable = 92
    gem = 93
    weapon_bow = 94
    weapon_bow_unstrung = 95
    egg = 96
    newbie_item = 97
    tile_aligned = 98
    dragon_armour = 99
    compass = 100
    oil_consuming = 101
    healing_power_1 = 102
    healing_power_2 = 103
    healing_power_3 = 104
    healing_power_4 = 105
    healing_power_5 = 106
    healing = 107
    named = 108
    one_per_tile = 109
    bed = 110
    inside_only = 111
    no_bank = 112
    recycled = 113
    loaded = 114
    flickering = 115
    light_bright = 116
    vehicle = 117
    flower = 118
    improve_item = 119
    death_prot = 120
    tool_belt = 121
    royal = 122
    no_move = 123
    wind = 124
    dredge = 125
    mine_door = 126
    no_sell_back = 127
    spring_filled = 128
    decay_destroys = 129
    rechargeable = 130
    server_portal = 131
    trap = 132
    disarm_trap = 133
    vehicle_dragged = 134
    owner_destroyable = 135
    creature_wearable = 136
    no_nutrition = 137
    puppet = 138
    over_ride_enchant = 139
    meditation = 140
    transmutable = 141
    sign = 142
    streetlamp = 143
    visible_decay = 144
    bulk_container = 145
    bulk = 146
    mission = 147
    combine_cold = 148
    spawns_trees = 149
    kills_trees = 150
    crude = 151
    minable = 152
    enchant_jewelry = 153
    weapon_polearm = 154
    always_bankable = 155
    always_lit = 156
    not_mission = 157
    mass_production = 158
    can_have_inscription = 159
    no_work_parent = 160
    war_target = 161
    source_spring = 162
    source = 163
    color_component = 164
    tutorial = 165
    ten_per_tile = 166
    four_per_tile = 167
    ability = 168
    planted_flowerpot = 169
    equipment_slot = 170
    inventory_group = 171
    magical_staff = 172
    improve_uses_type_as_material = 173
    no_discard = 174
    instant_discard = 175
    transportable = 176
    war_machine = 177
    never_show_creation_window_option = 178
    brazier = 179
    uses_specified_container_volume = 180
    tent = 181
    use_material_and_kingdom = 182
    smearable = 183
    carpet = 184
    one_per_tile_border = 185
    nature_plantable = 186
    no_improve = 187
    tapestry = 188
    chall_newbie = 189
    unfinished_no_take = 190
    milk = 191
    cheese = 192
    cart = 193
    owner_turnable = 194
    owner_moveable = 195
    unfired = 196
    chair = 197
    lead_multiple_creatures = 198
    plantable = 199
    plant_one_a_week = 200
    hitch_target = 201
    spice = 205
    potable = 206
    no_create = 207
    food_group = 208
    cooker = 209
    tool_cooking = 210
    recipe_item = 211
    uses_food_state = 212
    fermented = 213
    distilled = 214
    sealable = 215
    use_real_template_icon = 216
    cooking_oil = 217
    hover = 218
    food_bonus_hot = 219
    food_bonus_cold = 220
    potted = 221
    can_be_papyrus_wrapped = 222
    can_be_raw_wrapped = 223
    can_be_cloth_wrapped = 224
    surface_only = 225
    mushroom = 226
    harvestable = 227
    show_raw = 228
    not_spell_target = 229
    trellis = 230
    ingredients_only = 231
    component_item = 232
    uses_real_template = 233
    larder = 234
    rune = 235
    pegable = 236
    decay_on_deed = 237
    insulated = 238
    guard_tower = 239
    parent_on_ground = 240
    road_marker = 241
    paveable = 242
    cave_paveable = 243
    decoration_when_planted = 244
    desc_is_name = 245
    any_cereal_food_group = 1157
    any_veggie_food_group = 1156
    any_cheese_food_group = 1198
    any_milk_food_group = 1200
    any_meat_food_group = 1261
    any_fish_food_group = 1201
    any_mushroom_food_group = 1199
    any_herb_food_group = 1158
    any_flower_food_group = 1267
    any_berry_food_group = 1179
    any_nut_food_group = 1197
    any_fruit_food_group = 1163
    any_spice_food_group = 1159


class ItemTemplate(Enum):
    NONE = dict({'name': 'none', 'ItemTemplateId': -1})
    GREEN_APPLE = dict({'name': 'green apple', 'ItemTemplateId': 6})
    HAND = dict({'name': 'hand', 'ItemTemplateId': 14})
    SHAFT = dict({'name': 'shaft', 'ItemTemplateId': 23})
    BARLEY = dict({'name': 'barley', 'ItemTemplateId': 28})
    WHEAT = dict({'name': 'wheat', 'ItemTemplateId': 29})
    RYE = dict({'name': 'rye', 'ItemTemplateId': 30})
    OAT = dict({'name': 'oat', 'ItemTemplateId': 31})
    CORN = dict({'name': 'corn', 'ItemTemplateId': 32})
    PUMPKIN = dict({'name': 'pumpkin', 'ItemTemplateId': 33})
    PUMPKIN_SEED = dict({'name': 'pumpkin seed', 'ItemTemplateId': 34})
    POTATO = dict({'name': 'potato', 'ItemTemplateId': 35})
    CAMPFIRE = dict({'name': 'campfire', 'ItemTemplateId': 37})
    CHEESE_DRILL = dict({'name': 'cheese drill', 'ItemTemplateId': 65})
    CHEESE = dict({'name': 'cheese', 'ItemTemplateId': 66})
    GOAT_CHEESE = dict({'name': 'goat cheese', 'ItemTemplateId': 67})
    FETA_CHEESE = dict({'name': 'feta cheese', 'ItemTemplateId': 68})
    BUFFALO_CHEESE = dict({'name': 'buffalo cheese', 'ItemTemplateId': 69})
    HONEY = dict({'name': 'honey', 'ItemTemplateId': 70})
    LYE = dict({'name': 'lye', 'ItemTemplateId': 73})
    FRYING_PAN = dict({'name': 'frying pan', 'ItemTemplateId': 75})
    POTTERY_JAR = dict({'name': 'pottery jar', 'ItemTemplateId': 76})
    POTTERY_BOWL = dict({'name': 'pottery bowl', 'ItemTemplateId': 77})
    MEAT = dict({'name': 'meat', 'ItemTemplateId': 92})
    BUTCHERING_KNIFE = dict({'name': 'butchering knife', 'ItemTemplateId': 93})
    HANDLE = dict({'name': 'handle', 'ItemTemplateId': 99})
    WATER = dict({'name': 'water', 'ItemTemplateId': 128})
    COOKED_MEAT = dict({'name': 'cooked meat', 'ItemTemplateId': 129})
    CANDLE = dict({'name': 'candle', 'ItemTemplateId': 133})
    HAZELNUTS = dict({'name': 'hazelnuts', 'ItemTemplateId': 134})
    FAT = dict({'name': 'fat', 'ItemTemplateId': 140})
    MILK = dict({'name': 'milk', 'ItemTemplateId': 142})
    COTTON_SEED = dict({'name': 'cotton seed', 'ItemTemplateId': 145})
    PIKE = dict({'name': 'pike', 'ItemTemplateId': 157})
    SMALLMOUTH_BASS = dict({'name': 'smallmouth bass', 'ItemTemplateId': 158})
    HERRING = dict({'name': 'herring', 'ItemTemplateId': 159})
    CATFISH = dict({'name': 'catfish', 'ItemTemplateId': 160})
    SNOOK = dict({'name': 'snook', 'ItemTemplateId': 161})
    ROACH = dict({'name': 'roach', 'ItemTemplateId': 162})
    PERCH = dict({'name': 'perch', 'ItemTemplateId': 163})
    CARP = dict({'name': 'carp', 'ItemTemplateId': 164})
    BROOK_TROUT = dict({'name': 'brook trout', 'ItemTemplateId': 165})
    WOOD_SCRAP = dict({'name': 'wood scrap', 'ItemTemplateId': 169})
    LEATHER_PIECES = dict({'name': 'leather pieces', 'ItemTemplateId': 172})
    PIG_FOOD = dict({'name': 'pig food', 'ItemTemplateId': 173})
    OVEN = dict({'name': 'oven', 'ItemTemplateId': 178})
    FORGE = dict({'name': 'forge', 'ItemTemplateId': 180})
    DOUGH = dict({'name': 'dough', 'ItemTemplateId': 200})
    FLOUR = dict({'name': 'flour', 'ItemTemplateId': 201})
    GRINDSTONE = dict({'name': 'grindstone', 'ItemTemplateId': 202})
    BREAD = dict({'name': 'bread', 'ItemTemplateId': 203})
    GREEN_MUSHROOM = dict({'name': 'green mushroom', 'ItemTemplateId': 246})
    BLACK_MUSHROOM = dict({'name': 'black mushroom', 'ItemTemplateId': 247})
    BROWN_MUSHROOM = dict({'name': 'brown mushroom', 'ItemTemplateId': 248})
    YELLOW_MUSHROOM = dict({'name': 'yellow mushroom', 'ItemTemplateId': 249})
    BLUE_MUSHROOM = dict({'name': 'blue mushroom', 'ItemTemplateId': 250})
    RED_MUSHROOM = dict({'name': 'red mushroom', 'ItemTemplateId': 251})
    SPOON = dict({'name': 'spoon', 'ItemTemplateId': 257})
    KNIFE = dict({'name': 'knife', 'ItemTemplateId': 258})
    FORK = dict({'name': 'fork', 'ItemTemplateId': 259})
    CORPSE = dict({'name': 'corpse', 'ItemTemplateId': 272})
    OPEN_HELM = dict({'name': 'open helm', 'ItemTemplateId': 287})
    TOOTH = dict({'name': 'tooth', 'ItemTemplateId': 303})
    HORN = dict({'name': 'horn', 'ItemTemplateId': 304})
    HOOF = dict({'name': 'hoof', 'ItemTemplateId': 306})
    TAIL = dict({'name': 'tail', 'ItemTemplateId': 307})
    EYE = dict({'name': 'eye', 'ItemTemplateId': 308})
    BLADDER = dict({'name': 'bladder', 'ItemTemplateId': 309})
    GLAND = dict({'name': 'gland', 'ItemTemplateId': 310})
    TWISTED_HORN = dict({'name': 'twisted horn', 'ItemTemplateId': 311})
    LONG_HORN = dict({'name': 'long horn', 'ItemTemplateId': 312})
    STEW = dict({'name': 'stew', 'ItemTemplateId': 345})
    CASSEROLE = dict({'name': 'casserole', 'ItemTemplateId': 346})
    MEAL = dict({'name': 'meal', 'ItemTemplateId': 347})
    GULASCH = dict({'name': 'gulasch', 'ItemTemplateId': 348})
    SALT = dict({'name': 'salt', 'ItemTemplateId': 349})
    SAUCE_PAN = dict({'name': 'sauce pan', 'ItemTemplateId': 350})
    CAULDRON = dict({'name': 'cauldron', 'ItemTemplateId': 351})
    SOUP = dict({'name': 'soup', 'ItemTemplateId': 352})
    LOVAGE = dict({'name': 'lovage', 'ItemTemplateId': 353})
    SAGE = dict({'name': 'sage', 'ItemTemplateId': 354})
    ONION = dict({'name': 'onion', 'ItemTemplateId': 355})
    GARLIC = dict({'name': 'garlic', 'ItemTemplateId': 356})
    OREGANO = dict({'name': 'oregano', 'ItemTemplateId': 357})
    PARSLEY = dict({'name': 'parsley', 'ItemTemplateId': 358})
    BASIL = dict({'name': 'basil', 'ItemTemplateId': 359})
    THYME = dict({'name': 'thyme', 'ItemTemplateId': 360})
    BELLADONNA = dict({'name': 'belladonna', 'ItemTemplateId': 361})
    STRAWBERRIES = dict({'name': 'strawberries', 'ItemTemplateId': 362})
    ROSEMARY = dict({'name': 'rosemary', 'ItemTemplateId': 363})
    BLUEBERRY = dict({'name': 'blueberry', 'ItemTemplateId': 364})
    NETTLES = dict({'name': 'nettles', 'ItemTemplateId': 365})
    SASSAFRAS = dict({'name': 'sassafras', 'ItemTemplateId': 366})
    LINGONBERRY = dict({'name': 'lingonberry', 'ItemTemplateId': 367})
    MEAT_FILLET = dict({'name': 'meat fillet', 'ItemTemplateId': 368})
    FISH_FILLET = dict({'name': 'fish fillet', 'ItemTemplateId': 369})
    PORRIDGE = dict({'name': 'porridge', 'ItemTemplateId': 373})
    CHERRIES = dict({'name': 'cherries', 'ItemTemplateId': 409})
    LEMON = dict({'name': 'lemon', 'ItemTemplateId': 410})
    BLUE_GRAPES = dict({'name': 'blue grapes', 'ItemTemplateId': 411})
    OLIVES = dict({'name': 'olives', 'ItemTemplateId': 412})
    FRUIT_PRESS = dict({'name': 'fruit press', 'ItemTemplateId': 413})
    GREEN_GRAPES = dict({'name': 'green grapes', 'ItemTemplateId': 414})
    MAPLE_SYRUP = dict({'name': 'maple syrup', 'ItemTemplateId': 415})
    MAPLE_SAP = dict({'name': 'maple sap', 'ItemTemplateId': 416})
    FRUIT_JUICE = dict({'name': 'fruit juice', 'ItemTemplateId': 417})
    OLIVE_OIL = dict({'name': 'olive oil', 'ItemTemplateId': 418})
    RED_WINE = dict({'name': 'red wine', 'ItemTemplateId': 419})
    WHITE_WINE = dict({'name': 'white wine', 'ItemTemplateId': 420})
    CAMELLIA = dict({'name': 'camellia', 'ItemTemplateId': 422})
    OLEANDER = dict({'name': 'oleander', 'ItemTemplateId': 423})
    LAVENDER_FLOWER = dict({'name': 'lavender flower', 'ItemTemplateId': 424})
    TEA = dict({'name': 'tea', 'ItemTemplateId': 425})
    ROSE_FLOWER = dict({'name': 'rose flower', 'ItemTemplateId': 426})
    LEMONADE = dict({'name': 'lemonade', 'ItemTemplateId': 427})
    JAM = dict({'name': 'jam', 'ItemTemplateId': 428})
    COCHINEAL = dict({'name': 'cochineal', 'ItemTemplateId': 439})
    EGG = dict({'name': 'egg', 'ItemTemplateId': 464})
    HUGE_EGG = dict({'name': 'huge egg', 'ItemTemplateId': 465})
    SANDWICH = dict({'name': 'sandwich', 'ItemTemplateId': 488})
    BOUQUET_OF_YELLOW_FLOWERS = dict({'name': 'bouquet of yellow flowers', 'ItemTemplateId': 498})
    BOUQUET_OF_ORANGE_RED_FLOWERS = dict({'name': 'bouquet of orange-red flowers', 'ItemTemplateId': 499})
    BOUQUET_OF_PURPLE_FLOWERS = dict({'name': 'bouquet of purple flowers', 'ItemTemplateId': 500})
    BOUQUET_OF_WHITE_FLOWERS = dict({'name': 'bouquet of white flowers', 'ItemTemplateId': 501})
    BOUQUET_OF_BLUE_FLOWERS = dict({'name': 'bouquet of blue flowers', 'ItemTemplateId': 502})
    BOUQUET_OF_GREENISH_YELLOW_FLOWERS = dict({'name': 'bouquet of greenish-yellow flowers', 'ItemTemplateId': 503})
    BOUQUET_OF_WHITE_DOTTED_FLOWERS = dict({'name': 'bouquet of white-dotted flowers', 'ItemTemplateId': 504})
    MARLIN = dict({'name': 'marlin', 'ItemTemplateId': 569})
    BLUE_SHARK = dict({'name': 'blue shark', 'ItemTemplateId': 570})
    WHITE_SHARK = dict({'name': 'white shark', 'ItemTemplateId': 571})
    OCTOPUS = dict({'name': 'octopus', 'ItemTemplateId': 572})
    SAILFISH = dict({'name': 'sailfish', 'ItemTemplateId': 573})
    DORADO = dict({'name': 'dorado', 'ItemTemplateId': 574})
    TUNA = dict({'name': 'tuna', 'ItemTemplateId': 575})
    DISHWATER = dict({'name': 'dishwater', 'ItemTemplateId': 634})
    HEART = dict({'name': 'heart', 'ItemTemplateId': 636})
    SLEEP_POWDER = dict({'name': 'sleep powder', 'ItemTemplateId': 666})
    BRANCH = dict({'name': 'branch', 'ItemTemplateId': 688})
    CAKE = dict({'name': 'cake', 'ItemTemplateId': 729})
    CAKE_SLICE = dict({'name': 'cake slice', 'ItemTemplateId': 730})
    REED_FIBRE = dict({'name': 'reed fibre', 'ItemTemplateId': 745})
    RICE = dict({'name': 'rice', 'ItemTemplateId': 746})
    PRESS = dict({'name': 'press', 'ItemTemplateId': 747})
    PAPYRUS_SHEET = dict({'name': 'papyrus sheet', 'ItemTemplateId': 748})
    STRAWBERRY_SEEDS = dict({'name': 'strawberry seeds', 'ItemTemplateId': 750})
    BLACK_INK = dict({'name': 'black ink', 'ItemTemplateId': 753})
    COOKED_RICE = dict({'name': 'cooked rice', 'ItemTemplateId': 754})
    KELP = dict({'name': 'kelp', 'ItemTemplateId': 755})
    SOURCE = dict({'name': 'source', 'ItemTemplateId': 763})
    SOURCE_SALT = dict({'name': 'source salt', 'ItemTemplateId': 764})
    WINE_BARREL = dict({'name': 'wine barrel', 'ItemTemplateId': 768})
    WALNUT = dict({'name': 'walnut', 'ItemTemplateId': 832})
    CHESTNUT = dict({'name': 'chestnut', 'ItemTemplateId': 833})
    RICE_PORRIDGE = dict({'name': 'rice porridge', 'ItemTemplateId': 856})
    RISOTTO = dict({'name': 'risotto', 'ItemTemplateId': 857})
    RICE_WINE = dict({'name': 'rice wine', 'ItemTemplateId': 858})
    CRAB_MEAT = dict({'name': 'crab meat', 'ItemTemplateId': 900})
    SHEEP_MILK = dict({'name': 'sheep milk', 'ItemTemplateId': 1012})
    BISON_MILK = dict({'name': 'bison milk', 'ItemTemplateId': 1013})
    RIFT_WOOD = dict({'name': 'rift wood', 'ItemTemplateId': 1104})
    MINT = dict({'name': 'mint', 'ItemTemplateId': 1130})
    FENNEL = dict({'name': 'fennel', 'ItemTemplateId': 1131})
    FENNEL_PLANT = dict({'name': 'fennel plant', 'ItemTemplateId': 1132})
    CARROT = dict({'name': 'carrot', 'ItemTemplateId': 1133})
    CABBAGE = dict({'name': 'cabbage', 'ItemTemplateId': 1134})
    TOMATO = dict({'name': 'tomato', 'ItemTemplateId': 1135})
    SUGAR_BEET = dict({'name': 'sugar beet', 'ItemTemplateId': 1136})
    LETTUCE = dict({'name': 'lettuce', 'ItemTemplateId': 1137})
    PEA_POD = dict({'name': 'pea pod', 'ItemTemplateId': 1138})
    SUGAR = dict({'name': 'sugar', 'ItemTemplateId': 1139})
    CUMIN = dict({'name': 'cumin', 'ItemTemplateId': 1140})
    GINGER = dict({'name': 'ginger', 'ItemTemplateId': 1141})
    NUTMEG = dict({'name': 'nutmeg', 'ItemTemplateId': 1142})
    PAPRIKA = dict({'name': 'paprika', 'ItemTemplateId': 1143})
    TURMERIC = dict({'name': 'turmeric', 'ItemTemplateId': 1144})
    CARROT_SEED = dict({'name': 'carrot seed', 'ItemTemplateId': 1145})
    CABBAGE_SEED = dict({'name': 'cabbage seed', 'ItemTemplateId': 1146})
    TOMATO_SEED = dict({'name': 'tomato seed', 'ItemTemplateId': 1147})
    SUGAR_BEET_SEED = dict({'name': 'sugar beet seed', 'ItemTemplateId': 1148})
    LETTUCE_SEED = dict({'name': 'lettuce seed', 'ItemTemplateId': 1149})
    PEA = dict({'name': 'pea', 'ItemTemplateId': 1150})
    FENNEL_SEED = dict({'name': 'fennel seed', 'ItemTemplateId': 1151})
    COCOA = dict({'name': 'cocoa', 'ItemTemplateId': 1152})
    PAPRIKA_SEED = dict({'name': 'paprika seed', 'ItemTemplateId': 1153})
    TURMERIC_SEED = dict({'name': 'turmeric seed', 'ItemTemplateId': 1154})
    COCOA_BEAN = dict({'name': 'cocoa bean', 'ItemTemplateId': 1155})
    ANY_VEG = dict({'name': 'any veg', 'ItemTemplateId': 1156})
    ANY_CEREAL = dict({'name': 'any cereal', 'ItemTemplateId': 1157})
    ANY_HERB = dict({'name': 'any herb', 'ItemTemplateId': 1158})
    ANY_SPICE = dict({'name': 'any spice', 'ItemTemplateId': 1159})
    ANY_FRUIT = dict({'name': 'any fruit', 'ItemTemplateId': 1163})
    PIE_DISH = dict({'name': 'pie dish', 'ItemTemplateId': 1165})
    CAKE_TIN = dict({'name': 'cake tin', 'ItemTemplateId': 1166})
    BAKING_STONE = dict({'name': 'baking stone', 'ItemTemplateId': 1167})
    ROASTING_DISH = dict({'name': 'roasting dish', 'ItemTemplateId': 1169})
    SLICE_OF_BREAD = dict({'name': 'slice of bread', 'ItemTemplateId': 1170})
    PLATE = dict({'name': 'plate', 'ItemTemplateId': 1173})
    BATTER = dict({'name': 'batter', 'ItemTemplateId': 1174})
    FUDGE_SAUCE = dict({'name': 'fudge sauce', 'ItemTemplateId': 1176})
    PIE = dict({'name': 'pie', 'ItemTemplateId': 1177})
    STILL = dict({'name': 'still', 'ItemTemplateId': 1178})
    ANY_BERRY = dict({'name': 'any berry', 'ItemTemplateId': 1179})
    MEAD = dict({'name': 'mead', 'ItemTemplateId': 1180})
    CIDER = dict({'name': 'cider', 'ItemTemplateId': 1181})
    BEER = dict({'name': 'beer', 'ItemTemplateId': 1182})
    WHISKY = dict({'name': 'whisky', 'ItemTemplateId': 1183})
    PINENUT = dict({'name': 'pinenut', 'ItemTemplateId': 1184})
    CHOCOLATE = dict({'name': 'chocolate', 'ItemTemplateId': 1185})
    BUTTER = dict({'name': 'butter', 'ItemTemplateId': 1186})
    OMELETTE = dict({'name': 'omelette', 'ItemTemplateId': 1187})
    CURRY = dict({'name': 'curry', 'ItemTemplateId': 1188})
    SALAD = dict({'name': 'salad', 'ItemTemplateId': 1189})
    SAUSAGE = dict({'name': 'sausage', 'ItemTemplateId': 1190})
    BACON = dict({'name': 'bacon', 'ItemTemplateId': 1191})
    CORN_DOUGH = dict({'name': 'corn dough', 'ItemTemplateId': 1192})
    COOKING_OIL = dict({'name': 'cooking oil', 'ItemTemplateId': 1193})
    GRAVY = dict({'name': 'gravy', 'ItemTemplateId': 1194})
    CUSTARD = dict({'name': 'custard', 'ItemTemplateId': 1195})
    RASPBERRIES = dict({'name': 'raspberries', 'ItemTemplateId': 1196})
    ANY_NUT = dict({'name': 'any nut', 'ItemTemplateId': 1197})
    ANY_CHEESE = dict({'name': 'any cheese', 'ItemTemplateId': 1198})
    ANY_MUSHROOM = dict({'name': 'any mushroom', 'ItemTemplateId': 1199})
    ANY_MILK = dict({'name': 'any milk', 'ItemTemplateId': 1200})
    ANY_FISH = dict({'name': 'any fish', 'ItemTemplateId': 1201})
    BISCUIT = dict({'name': 'biscuit', 'ItemTemplateId': 1202})
    FRIES = dict({'name': 'fries', 'ItemTemplateId': 1203})
    GELATINE = dict({'name': 'gelatine', 'ItemTemplateId': 1204})
    HONEY_WATER = dict({'name': 'honey water', 'ItemTemplateId': 1205})
    PASSATA = dict({'name': 'passata', 'ItemTemplateId': 1206})
    PASTA = dict({'name': 'pasta', 'ItemTemplateId': 1207})
    PASTRY = dict({'name': 'pastry', 'ItemTemplateId': 1208})
    PESTO = dict({'name': 'pesto', 'ItemTemplateId': 1209})
    STOCK = dict({'name': 'stock', 'ItemTemplateId': 1210})
    TOMATO_KETCHUP = dict({'name': 'tomato ketchup', 'ItemTemplateId': 1211})
    WHITE_SAUCE = dict({'name': 'white sauce', 'ItemTemplateId': 1212})
    WORT = dict({'name': 'wort', 'ItemTemplateId': 1213})
    RAT_ON_A_STICK = dict({'name': 'rat-on-a-stick', 'ItemTemplateId': 1214})
    HOG_ROAST = dict({'name': 'hog roast', 'ItemTemplateId': 1215})
    LAMB_SPIT = dict({'name': 'lamb spit', 'ItemTemplateId': 1216})
    MUSHY_PEAS = dict({'name': 'mushy peas', 'ItemTemplateId': 1217})
    CROUTONS = dict({'name': 'croutons', 'ItemTemplateId': 1218})
    HAGGIS = dict({'name': 'haggis', 'ItemTemplateId': 1219})
    CORNFLOUR = dict({'name': 'cornflour', 'ItemTemplateId': 1220})
    CHEESECAKE = dict({'name': 'cheesecake', 'ItemTemplateId': 1221})
    KIELBASA = dict({'name': 'kielbasa', 'ItemTemplateId': 1222})
    MUSHROOM = dict({'name': 'mushroom', 'ItemTemplateId': 1223})
    STUFFED_MUSHROOM = dict({'name': 'stuffed mushroom', 'ItemTemplateId': 1224})
    CRISPS = dict({'name': 'crisps', 'ItemTemplateId': 1225})
    JELLY = dict({'name': 'jelly', 'ItemTemplateId': 1226})
    SCONE = dict({'name': 'scone', 'ItemTemplateId': 1227})
    TOAST = dict({'name': 'toast', 'ItemTemplateId': 1228})
    PASTY = dict({'name': 'pasty', 'ItemTemplateId': 1229})
    CHOCOLATE_NUT_SPREAD = dict({'name': 'chocolate nut spread', 'ItemTemplateId': 1230})
    VODKA = dict({'name': 'vodka', 'ItemTemplateId': 1231})
    BRANDY = dict({'name': 'brandy', 'ItemTemplateId': 1232})
    MOONSHINE = dict({'name': 'moonshine', 'ItemTemplateId': 1233})
    GIN = dict({'name': 'gin', 'ItemTemplateId': 1234})
    PINEAPPLE = dict({'name': 'pineapple', 'ItemTemplateId': 1235})
    SAUSAGE_SKIN = dict({'name': 'sausage skin', 'ItemTemplateId': 1236})
    MORTAR_AND_PESTLE = dict({'name': 'mortar and pestle', 'ItemTemplateId': 1237})
    ROCK_SALT = dict({'name': 'rock salt', 'ItemTemplateId': 1238})
    SPAGHETTI = dict({'name': 'spaghetti', 'ItemTemplateId': 1240})
    ICING = dict({'name': 'icing', 'ItemTemplateId': 1241})
    CAKE_MIX = dict({'name': 'cake mix', 'ItemTemplateId': 1242})
    BREADCRUMBS = dict({'name': 'breadcrumbs', 'ItemTemplateId': 1244})
    MEATBALLS = dict({'name': 'meatballs', 'ItemTemplateId': 1245})
    VINEGAR = dict({'name': 'vinegar', 'ItemTemplateId': 1246})
    CUCUMBER = dict({'name': 'cucumber', 'ItemTemplateId': 1247})
    CUCUMBER_SEED = dict({'name': 'cucumber seed', 'ItemTemplateId': 1248})
    CREAM = dict({'name': 'cream', 'ItemTemplateId': 1249})
    GOBLIN_SKULL = dict({'name': 'goblin skull', 'ItemTemplateId': 1250})
    BISCUIT_MIX = dict({'name': 'biscuit mix', 'ItemTemplateId': 1256})
    SCONE_MIX = dict({'name': 'scone mix', 'ItemTemplateId': 1257})
    TART = dict({'name': 'tart', 'ItemTemplateId': 1258})
    STIR_FRY = dict({'name': 'stir fry', 'ItemTemplateId': 1259})
    NORI = dict({'name': 'nori', 'ItemTemplateId': 1260})
    ANY_MEAT = dict({'name': 'any meat', 'ItemTemplateId': 1261})
    PIZZA = dict({'name': 'pizza', 'ItemTemplateId': 1262})
    ANY_OIL = dict({'name': 'any oil', 'ItemTemplateId': 1263})
    SUSHI = dict({'name': 'sushi', 'ItemTemplateId': 1264})
    PICKLE = dict({'name': 'pickle', 'ItemTemplateId': 1265})
    PUDDING = dict({'name': 'pudding', 'ItemTemplateId': 1266})
    ANY_FLOWER = dict({'name': 'any flower', 'ItemTemplateId': 1267})
    BROTH = dict({'name': 'broth', 'ItemTemplateId': 1268})
    WOOD_PULP = dict({'name': 'wood pulp', 'ItemTemplateId': 1270})
    PAPER_SHEET = dict({'name': 'paper sheet', 'ItemTemplateId': 1272})
    HOPS = dict({'name': 'hops', 'ItemTemplateId': 1273})
    SNOWBALL = dict({'name': 'snowball', 'ItemTemplateId': 1276})
    COCONUT = dict({'name': 'coconut', 'ItemTemplateId': 1280})
    ICE_CREAM = dict({'name': 'ice cream', 'ItemTemplateId': 1281})
    SWEET = dict({'name': 'sweet', 'ItemTemplateId': 1282})
    ORANGE = dict({'name': 'orange', 'ItemTemplateId': 1283})
    BOILER = dict({'name': 'boiler', 'ItemTemplateId': 1284})
    RUM = dict({'name': 'rum', 'ItemTemplateId': 1286})
    MUFFIN = dict({'name': 'muffin', 'ItemTemplateId': 1287})
    COOKIE = dict({'name': 'cookie', 'ItemTemplateId': 1288})

    def __init__(self):
        self.templateId = 0
        self.name = ""
        self.time = 0


class Cooker(Enum):
    CAMPFIRE = dict({'itemTemplate': ItemTemplate.CAMPFIRE})
    OVEN = dict({'itemTemplate': ItemTemplate.OVEN})
    FORGE = dict({'itemTemplate': ItemTemplate.FORGE})

    def __init__(self):
        self.itemTemplate = ItemTemplate.NONE
        self.difficulty = 0
        self.rarity = Rarity.ANY
    pass


class Container(Enum):

    def __init__(self):
        self.itemTemplate = ItemTemplate.NONE
        self.difficulty = 0
    pass


class CState(Enum):
    RAW =



class Active:
    def __init__(self):
        self.itemTemplate = ItemTemplate.NONE
        self.cstate = ""
        self.pstate = ""
        self.material = ""
        self.realtemplate = ItemTemplate.NONE
        self.difficulty = 0
        self.loss = 0
        self.ratio = 0
    pass


class Target:
    pass


class Mandatory:
    pass


class Optional:
    pass


class OneOf:
    pass


class ZeroOrOne:
    pass


class OneOrMore:
    pass


class Any:
    pass